spring.application.name=crudspringbootdemo

spring.datasource.url=jdbc:mysql://localhost:3306/students_crud_db
spring.datasource.username=root
spring.datasource.password=Arish@629


spring.jpa.hibernate.ddl-auto=update

spring.web.error.include-message=always
